# Model arguments
model_name_or_path: xx
# model_name_or_path: xx
model_revision: main
model_trust_remote_code: true
torch_dtype: bfloat16
attn_implementation: flash_attention_2
bf16: true
tf32: true
output_dir: runs_output_grpo_commonsense/qwen3_nochaijie_1e-6

# Dataset arguments
dataset_id_or_path: xxx/CommonsenseQA/指令微调数据/不拆解_GRPO/grpo_new.json

# Lora Arguments
# No LoRA is used here
use_peft: true
lora_r: 8
lora_alpha: 16
lora_target_modules: ["q_proj", "k_proj", "v_proj", "o_proj"]
# lora_target_modules: ["all_linear"]

# Training arguments
max_steps: -1
per_device_train_batch_size: 3
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 1e-6 # 1.0e-6 as in the deepseek math paper 5-e7 from https://hijkzzz.notion.site/unraveling-rlhf-and-its-variants-engineering-insights#147d9a33ecc9806090f3d5c749d31f05
num_train_epochs: 2
lr_scheduler_type: cosine
warmup_ratio: 0.03
# GRPO specific parameters
beta: 0.001 # 0.04 as in the deepseek math paper 0.001 from https://hijkzzz.notion.site/unraveling-rlhf-and-its-variants-engineering-insights#147d9a33ecc9806090f3d5c749d31f05
max_prompt_length: 650
max_completion_length: 550
num_generations: 6
trust_remote_code: true

use_vllm: false
# use_vllm: true
# vllm_device: "cuda:2"
# vllm_gpu_memory_utilization: 0.35
# vllm_max_model_len: 2000
# vllm_temperature: 0.7

# Logging arguments
logging_strategy: steps
logging_steps: 2
report_to:
- tensorboard
save_strategy: "steps"
save_steps: 200
seed: 42

# Hugging Face Hub 
push_to_hub: false
  # hub_model_id: llama-3-1-8b-math-orca-qlora-10k-ep1 # if not defined same as output_dir
